### ISSUE TITLE
CodeAttributeDeclaration is missing a period

### ISSUE THREAD

**Issue by stphnlwlsh** [zijianhuang/openapiclientgen#61]
For date only, the `.` character is missing for a namespace.

See PR for fix.

**Comment by zijianhuang** [comment]
merged approved. and v3.0.1 released.

just our of curiosity. the offending feature is basically for .NET Framework and .NET Core prior to .NET 6. Do you happen to be using these? or somehow have other design consideration even when using .NET 6 or above?

**Comment by stphnlwlsh** [comment]
We have a .NETStandard project where the types are shared. That may be the issue.
